# config map
# masalah dengan hardcode konfigurasi
# 1. saat kita meng-hardcode konfigurasi environment variable file yaml di kubernetes, artinya kita harus siap-siap membuat file konfigurasi yg berbeda-beda tiap jenis environment
# 2. misal jika kita punya environment production, development, dan qa. kita harus membuat file untuk tiap environment
# 3. jika sampai kita lupa meng-update file konfigurasi, maka kita bisa menggunakan konfigurasi yg salah

# kubernetes memiliki kemampuan untuk memisahkan konfigurasi dalam object beranam ConfigMap
# sederhananya, ConfigMap berisi key-value
# Aplikasi tidak perlu membaca konfigurasi langsung ke ConfigMap. melainkan kubernetes akan mengirim konfigurasi di ConfigMap ke dalam environment variable di Container

# kubectl create -f config-map.yaml

# kubectl decribe configmap name-configmap

# templace
apiVersion: v1
kind: ConfigMap
data:
  ENV_KEY: "ENV_VALUE"
metadata:
  name: configmap-name

---
# example
apiVersion: v1
kind: ConfigMap
metadata:
  name: nodejs-env-config
data:
  APPLICATION: "My Cool Application"
  VERSION: "1.0.0"

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nodejs-rs # nama dari Replica Set yg akan dibuat
  labels:
    rs-name: nodejs-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      pod-name: nodejs-env # Pod yg akan dipilih oleh replica set
  template: # template untuk membuat Pod
    metadata:
      name: nodejs-env # nama Pod yg akan dibuat
      labels: # label Pod yg akan dibuat
        pod-name: nodejs-env
    spec:
      containers:
        - name: nodejs-env # nama Container yg akan dijalankan di dalam Pod
          image: khannedy/nodejs-env
          ports:
            - containerPort: 80
          envFrom: # ENV yg akan diovveride Container
            - configMapRef:
                name: nodejs-env-config

---

apiVersion: v1
kind: Service
metadata:
  name: nodejs-env-service
  labels:
    service-name: nodejs-env-service
spec:
  selector:
    pod-name: nodejs-env
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
